In [4]:
#bingo 
import random, numpy
def generate_card():
    number = 25
    max_number = 50
    array = []
    while len(array) < number:
        new_num = random.randint(0,max_number)
        if new_num not in array:
            array.append(new_num)

    arr = numpy.array(array)

    bingo_card = arr.reshape(5, 5)
    return bingo_card

def number_caller():
    bingo = False
    number_called = []
    max_number = 50
    while not bingo and len(number_called) <= max_number: 
        num = random.randint(0,max_number)
        if num not in number_called:
            print(num)
            number_called.append(num)
            bingo_reached = input("Has a player reached bingo? Enter 'Y' or 'N' ")
            if bingo_reached.upper() == "Y":
                print("Well Done to the winner!")
                bingo = True
    
        
num_of_players = int(input("How many players? "))

for counter in range(0,num_of_players):
    print(generate_card())
    print()
    print()

print("Time to start the game!")
number_caller()

How many players? 2
[[11 44  8 28 47]
 [32 38 13 21 49]
 [12  2 29 40  0]
 [45  4 14  5  9]
 [ 3 33 36 19 18]]


[[48  1 32  4 11]
 [21 46 17  5 33]
 [30 10 49 35 12]
 [41 31  9 13 42]
 [ 6 39 38 45 43]]


Time to start the game!
25
Has a player reached bingo? Enter 'Y' or 'N' n
34
Has a player reached bingo? Enter 'Y' or 'N' n
1
Has a player reached bingo? Enter 'Y' or 'N' n
30
Has a player reached bingo? Enter 'Y' or 'N' n
19
Has a player reached bingo? Enter 'Y' or 'N' n
0
Has a player reached bingo? Enter 'Y' or 'N' n
18
Has a player reached bingo? Enter 'Y' or 'N' n
5
Has a player reached bingo? Enter 'Y' or 'N' n
21
Has a player reached bingo? Enter 'Y' or 'N' n
22
Has a player reached bingo? Enter 'Y' or 'N' n
9
Has a player reached bingo? Enter 'Y' or 'N' n
26
Has a player reached bingo? Enter 'Y' or 'N' n
12
Has a player reached bingo? Enter 'Y' or 'N' n
17
Has a player reached bingo? Enter 'Y' or 'N' y
Well Done to the winner!
